version: '3'
services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=test
    ports:
      - 5432:5432
  crawler:
    build: .
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_HOST=db
    depends_on:
      - db
    volumes:
      - ./data:/app/data
